### PR TITLE
Support for remote images.

### PR DESCRIPTION
**Pull request by cupcakearmy**
With this PR your package will support remote images.

### CODE REVIEW

**Comment by cupcakearmy** [comment]
@matyunya is there some interest for this? If yes, I'll resolve the conflict

**Comment by matyunya** [comment]
Sure, let's do it.

**Comment by cupcakearmy** [comment]
Done :)

**Comment by matyunya** [comment]
Thank you!

**Comment by cupcakearmy** [comment]
Thanks for all the setup work :)

**Comment by cupcakearmy** [comment]
@matyunya could you do a npm release with this? could use it xD

**Pull request merged**
